---
title: "Aeron Deployment for OCI"
description: "Deploy Aeron messaging system with controller, benchmark nodes, and optional failover for high-performance benchmarking on Oracle Cloud Infrastructure"
schemaVersion: 1.1.0
version: "1.0.0"
locale: "en"

logoUrl: https://raw.githubusercontent.com/real-logic/aeron/master/aeron-logo.png

outputs:
  controller_public_ip:
    title: "Controller Node Public IP"
    type: copyableString
    visible: true

  controller_ssh_command:
    title: "SSH Command (Controller)"
    type: copyableString
    visible: true

  client_node_ip:
    title: "Client Node Private IP"
    type: copyableString
    visible: true

  receiver_node_ip:
    title: "Receiver Node Private IP"
    type: copyableString
    visible: true

  failover_private_ip:
    title: "Failover Node Private IP"
    type: copyableString
    visible: true

  benchmark_command:
    title: "Benchmark Command"
    type: copyableString
    visible: true

variableGroups:
  - title: "Basic Configuration"
    variables:
      - compartment_ocid
      - ssh_public_key
      - use_custom_name
      - cluster_name

  - title: "Controller Node (Orchestrator - Public Subnet)"
    variables:
      - controller_ad
      - controller_shape
      - controller_ocpus
      - controller_memory_gb
      - controller_boot_volume_size_gb

  - title: "Benchmark Nodes (Client/Receiver - Private Subnet)"
    variables:
      - benchmark_ad
      - benchmark_node_count
      - benchmark_shape
      - benchmark_ocpus
      - benchmark_memory_gb
      - benchmark_boot_volume_size_gb

  - title: "Failover Node (Private Subnet - Different AD)"
    variables:
      - enable_failover_node
      - failover_ad
      - failover_shape
      - failover_ocpus
      - failover_memory_gb
      - failover_boot_volume_size_gb

  - title: "Performance Settings"
    variables:
      - hyperthreading

  - title: "Network Configuration"
    variables:
      - use_existing_vcn
      - vcn_compartment_ocid
      - existing_vcn_id
      - existing_public_subnet_id
      - existing_private_subnet_id
      - vcn_cidr_block
      - public_subnet_cidr
      - private_subnet_cidr
      - private_deployment

  - title: "Image Configuration"
    variables:
      - use_default_image
      - marketplace_image
      - custom_image_ocid

  - title: "Aeron Configuration"
    variables:
      - install_aeron
      - aeron_git_repo
      - aeron_git_branch
      - java_version
      - run_benchmarks

  - title: "Hidden Variables"
    variables:
      - tenancy_ocid
      - region
      - ssh_username
      - use_instance_principal
      - default_image_name
    visible: false

variables:
  tenancy_ocid:
    type: string
    title: "Tenancy OCID"
    required: true

  region:
    type: oci:identity:region:name
    title: "Region"
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "Compartment where resources will be created"
    required: true
    dependsOn:
      compartmentId: ${tenancy_ocid}

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "SSH Public Key"
    description: "Public SSH key for instance access"
    required: true

  use_custom_name:
    type: boolean
    title: "Use Custom Cluster Name"
    description: "Use a custom name instead of auto-generated"
    default: false

  cluster_name:
    type: string
    title: "Cluster Name"
    description: "Name prefix for all resources"
    default: "aeron"
    visible:
      eq:
        - ${use_custom_name}
        - true
    required: true

  # ==========================================================================
  # Controller Node Configuration (Public Subnet - Orchestrator)
  # ==========================================================================
  controller_ad:
    type: oci:identity:availabilitydomain:name
    title: "Controller Node Availability Domain"
    description: "AD for the controller/orchestrator node (deployed in public subnet)"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}

  controller_shape:
    type: oci:core:instanceshape:name
    title: "Controller Node Shape"
    description: "Compute shape for the controller (orchestrator only, smaller is fine)"
    default: "VM.Standard.E5.Flex"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}

  controller_ocpus:
    type: integer
    title: "Controller Node OCPUs"
    description: "Number of OCPUs for controller (orchestrator only, no minimum)"
    minimum: 1
    maximum: 64
    default: 2
    required: true
    visible:
      or:
        - eq:
            - ${controller_shape}
            - "VM.Standard.E3.Flex"
        - eq:
            - ${controller_shape}
            - "VM.Standard.E4.Flex"
        - eq:
            - ${controller_shape}
            - "VM.Standard.E5.Flex"
        - eq:
            - ${controller_shape}
            - "VM.Standard3.Flex"
        - eq:
            - ${controller_shape}
            - "VM.Optimized3.Flex"
        - eq:
            - ${controller_shape}
            - "VM.Standard.A1.Flex"

  controller_memory_gb:
    type: integer
    title: "Controller Node Memory (GB)"
    description: "Memory in GB for controller"
    minimum: 8
    maximum: 256
    default: 16
    required: true
    visible:
      or:
        - eq:
            - ${controller_shape}
            - "VM.Standard.E3.Flex"
        - eq:
            - ${controller_shape}
            - "VM.Standard.E4.Flex"
        - eq:
            - ${controller_shape}
            - "VM.Standard.E5.Flex"
        - eq:
            - ${controller_shape}
            - "VM.Standard3.Flex"
        - eq:
            - ${controller_shape}
            - "VM.Optimized3.Flex"
        - eq:
            - ${controller_shape}
            - "VM.Standard.A1.Flex"

  controller_boot_volume_size_gb:
    type: integer
    title: "Controller Boot Volume Size (GB)"
    minimum: 50
    maximum: 1024
    default: 100
    required: true

  # ==========================================================================
  # Benchmark Nodes Configuration (Private Subnet - Client/Receiver)
  # ==========================================================================
  benchmark_ad:
    type: oci:identity:availabilitydomain:name
    title: "Benchmark Nodes Availability Domain"
    description: "AD for benchmark nodes (client/receiver) - all deployed in same AD"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}

  benchmark_node_count:
    type: integer
    title: "Number of Benchmark Nodes"
    description: "Number of benchmark nodes to deploy (minimum 2 for client/receiver)"
    minimum: 2
    maximum: 10
    default: 2
    required: true

  benchmark_shape:
    type: oci:core:instanceshape:name
    title: "Benchmark Node Shape"
    description: "Compute shape for benchmark nodes (high performance recommended)"
    default: "VM.Standard.E5.Flex"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}

  benchmark_ocpus:
    type: integer
    title: "Benchmark Node OCPUs"
    description: "Number of OCPUs per benchmark node (minimum 10 for Aeron performance)"
    minimum: 10
    maximum: 128
    default: 10
    required: true
    visible:
      or:
        - eq:
            - ${benchmark_shape}
            - "VM.Standard.E3.Flex"
        - eq:
            - ${benchmark_shape}
            - "VM.Standard.E4.Flex"
        - eq:
            - ${benchmark_shape}
            - "VM.Standard.E5.Flex"
        - eq:
            - ${benchmark_shape}
            - "VM.Standard3.Flex"
        - eq:
            - ${benchmark_shape}
            - "VM.Optimized3.Flex"
        - eq:
            - ${benchmark_shape}
            - "VM.Standard.A1.Flex"

  benchmark_memory_gb:
    type: integer
    title: "Benchmark Node Memory (GB)"
    description: "Memory in GB per benchmark node"
    minimum: 16
    maximum: 1024
    default: 64
    required: true
    visible:
      or:
        - eq:
            - ${benchmark_shape}
            - "VM.Standard.E3.Flex"
        - eq:
            - ${benchmark_shape}
            - "VM.Standard.E4.Flex"
        - eq:
            - ${benchmark_shape}
            - "VM.Standard.E5.Flex"
        - eq:
            - ${benchmark_shape}
            - "VM.Standard3.Flex"
        - eq:
            - ${benchmark_shape}
            - "VM.Optimized3.Flex"
        - eq:
            - ${benchmark_shape}
            - "VM.Standard.A1.Flex"

  benchmark_boot_volume_size_gb:
    type: integer
    title: "Benchmark Boot Volume Size (GB)"
    minimum: 50
    maximum: 32768
    default: 200
    required: true

  # ==========================================================================
  # Failover Node Configuration (Private Subnet - Different AD)
  # ==========================================================================
  enable_failover_node:
    type: boolean
    title: "Enable Failover Node"
    description: "Create a failover node in a different Availability Domain"
    default: false

  failover_ad:
    type: oci:identity:availabilitydomain:name
    title: "Failover Node Availability Domain"
    description: "AD for failover node (must be different from benchmark nodes)"
    required: true
    visible:
      eq:
        - ${enable_failover_node}
        - true
    dependsOn:
      compartmentId: ${compartment_ocid}

  failover_shape:
    type: oci:core:instanceshape:name
    title: "Failover Node Shape"
    description: "Compute shape for the failover node"
    default: "VM.Standard.E5.Flex"
    required: true
    visible:
      eq:
        - ${enable_failover_node}
        - true
    dependsOn:
      compartmentId: ${compartment_ocid}

  failover_ocpus:
    type: integer
    title: "Failover Node OCPUs"
    description: "Number of OCPUs for failover node (minimum 10)"
    minimum: 10
    maximum: 128
    default: 10
    visible:
      eq:
        - ${enable_failover_node}
        - true

  failover_memory_gb:
    type: integer
    title: "Failover Node Memory (GB)"
    minimum: 16
    maximum: 1024
    default: 64
    visible:
      eq:
        - ${enable_failover_node}
        - true

  failover_boot_volume_size_gb:
    type: integer
    title: "Failover Boot Volume Size (GB)"
    minimum: 50
    maximum: 32768
    default: 200
    visible:
      eq:
        - ${enable_failover_node}
        - true

  # ==========================================================================
  # Performance Settings
  # ==========================================================================
  hyperthreading:
    type: boolean
    title: "Enable Hyperthreading (SMT)"
    description: "Disabled by default for optimal Aeron benchmarking performance (applies to benchmark/failover nodes only)"
    default: false

  # ==========================================================================
  # Network Configuration
  # ==========================================================================
  use_existing_vcn:
    type: boolean
    title: "Use Existing VCN"
    description: "Use an existing VCN instead of creating a new one"
    default: false

  vcn_compartment_ocid:
    type: oci:identity:compartment:id
    title: "VCN Compartment"
    description: "Compartment where VCN exists or will be created"
    default: ${compartment_ocid}
    dependsOn:
      compartmentId: ${tenancy_ocid}

  existing_vcn_id:
    type: oci:core:vcn:id
    title: "Existing VCN"
    description: "Select an existing VCN"
    visible:
      eq:
        - ${use_existing_vcn}
        - true
    dependsOn:
      compartmentId: ${vcn_compartment_ocid}

  existing_public_subnet_id:
    type: oci:core:subnet:id
    title: "Public Subnet (Controller)"
    description: "Select public subnet for controller node"
    visible:
      eq:
        - ${use_existing_vcn}
        - true
    dependsOn:
      compartmentId: ${vcn_compartment_ocid}
      vcnId: ${existing_vcn_id}
      hidePrivateSubnet: true

  existing_private_subnet_id:
    type: oci:core:subnet:id
    title: "Private Subnet (Benchmark/Failover)"
    description: "Select private subnet for benchmark and failover nodes"
    visible:
      eq:
        - ${use_existing_vcn}
        - true
    dependsOn:
      compartmentId: ${vcn_compartment_ocid}
      vcnId: ${existing_vcn_id}
      hidePublicSubnet: true

  vcn_cidr_block:
    type: string
    title: "VCN CIDR Block"
    description: "CIDR block for new VCN"
    default: "10.0.0.0/16"
    visible:
      eq:
        - ${use_existing_vcn}
        - false

  public_subnet_cidr:
    type: string
    title: "Public Subnet CIDR (Controller)"
    description: "CIDR for public subnet where controller is deployed"
    default: "10.0.0.0/24"
    visible:
      eq:
        - ${use_existing_vcn}
        - false

  private_subnet_cidr:
    type: string
    title: "Private Subnet CIDR (Benchmark/Failover)"
    description: "CIDR for private subnet where benchmark and failover nodes are deployed"
    default: "10.0.1.0/24"
    visible:
      eq:
        - ${use_existing_vcn}
        - false

  private_deployment:
    type: boolean
    title: "Private Deployment"
    description: "Deploy controller without public IP (requires VPN/FastConnect)"
    default: false

  # ==========================================================================
  # Image Configuration
  # ==========================================================================
  use_default_image:
    type: boolean
    title: "Use Default Image (Recommended)"
    description: "Use Ubuntu 24.04 Minimal - best for Aeron benchmarking"
    default: true

  default_image_name:
    type: string
    title: "Default Image"
    default: "Canonical-Ubuntu-24.04-Minimal-2025.01.31-0"

  marketplace_image:
    type: enum
    title: "Alternative Marketplace Image"
    description: "Select alternative image if not using default"
    enum:
      - "Canonical-Ubuntu-24.04-Minimal-2025.01.31-0"
      - "Canonical-Ubuntu-24.04-2025.01.31-0"
      - "Canonical-Ubuntu-22.04-Minimal-2025.01.30-0"
      - "Canonical-Ubuntu-22.04-2025.01.30-0"
    default: "Canonical-Ubuntu-24.04-Minimal-2025.01.31-0"
    visible:
      eq:
        - ${use_default_image}
        - false

  custom_image_ocid:
    type: string
    title: "Custom Image OCID"
    description: "Custom image OCID (overrides marketplace selection)"
    default: ""
    visible:
      eq:
        - ${use_default_image}
        - false

  # ==========================================================================
  # Aeron Configuration
  # ==========================================================================
  install_aeron:
    type: boolean
    title: "Install Aeron"
    description: "Install Aeron from Git and build from source"
    default: true

  aeron_git_repo:
    type: string
    title: "Aeron Git Repository"
    description: "Git repository URL for Aeron"
    default: "https://github.com/real-logic/aeron.git"
    visible:
      eq:
        - ${install_aeron}
        - true

  aeron_git_branch:
    type: string
    title: "Aeron Git Branch/Tag"
    description: "Branch or tag to checkout (leave empty for latest master)"
    default: ""
    visible:
      eq:
        - ${install_aeron}
        - true

  java_version:
    type: enum
    title: "Java Version"
    description: "OpenJDK version - 17 recommended for Aeron"
    enum:
      - "17"
      - "21"
    default: "17"
    visible:
      eq:
        - ${install_aeron}
        - true

  run_benchmarks:
    type: boolean
    title: "Run Benchmarks After Deployment"
    description: "Automatically run Aeron benchmarks after installation"
    default: false
    visible:
      eq:
        - ${install_aeron}
        - true

  ssh_username:
    type: string
    title: "SSH Username"
    description: "ubuntu for Ubuntu images"
    default: "ubuntu"

  use_instance_principal:
    type: boolean
    title: "Use Instance Principal"
    default: true
